# Generated by Django 3.1 on 2021-02-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDatabase',
            fields=[
                ('crypto_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('popular_link', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=10, max_digits=15)),
                ('marketcap', models.DecimalField(decimal_places=10, max_digits=25)),
                ('volume_24h', models.DecimalField(decimal_places=10, max_digits=25)),
                ('percent_change_24h', models.DecimalField(decimal_places=10, max_digits=15)),
                ('percent_change_1h', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
    ]
